image: docker:latest

services:
 - docker:dind

stages:
 - build
 - deploy

before_script:
 - docker info

build-docker:
    stage: build
    except:
        refs:
            - master
    script:
     - docker build -t gitlab-merge-resource .
     - docker tag gitlab-merge-resource udienz/gitlab-merge-resource:latest

openmerge:
    image: udienz/gitlab-merge-resource
    before_script: []
    stage: deploy
    except:
        refs:
            - master
    script:
        - HOST=${CI_PROJECT_URL} CI_PROJECT_ID=${CI_PROJECT_ID} CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME} GITLAB_USER_ID=${GITLAB_USER_ID} GITLAB_PRIVATE_TOKEN=${GITLAB_PRIVATE_TOKEN} $CI_PROJECT_DIR/utils/merge.sh
    when: on_success

publishsuccess:
    image: udienz/gitlab-merge-resource
    before_script: []
    stage: deploy
    except:
        refs:
            - master
    script:
        - HOST=${CI_PROJECT_URL} CI_PROJECT_ID=${CI_PROJECT_ID} CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME} GITLAB_USER_ID=${GITLAB_USER_ID} GITLAB_PRIVATE_TOKEN=${GITLAB_PRIVATE_TOKEN} $CI_PROJECT_DIR/utils/push-to-github.sh success
    when: on_success

publishfail:
    image: udienz/gitlab-merge-resource
    before_script: []
    stage: deploy
    except:
        refs:
            - master
    script:
        - HOST=${CI_PROJECT_URL} CI_PROJECT_ID=${CI_PROJECT_ID} CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME} GITLAB_USER_ID=${GITLAB_USER_ID} GITLAB_PRIVATE_TOKEN=${GITLAB_PRIVATE_TOKEN} $CI_PROJECT_DIR/utils/push-to-github.sh failure
    when: on_failure

