image: docker:latest

services:
 - docker:dind

stages:
 - build
 - deploy

before_script:
 - docker info

build-docker:
    stage: build
    except:
        refs:
            - master
    only:
        changes:
            - Dockerfile
    script:
     - docker build -t gitlab-merge-resource .
     - docker tag gitlab-merge-resource udienz/gitlab-merge-resource:latest
     - docker login -u="$DOCKERUSER" -p="$DOCKERPASS"
     - docker push udienz/gitlab-merge-resource:latest

include:
    - local: '/template/create-merge.yml'
    - local: '/template/publish-github-status.yml'
