image: docker:latest

services:
 - docker:dind

stages:
 - build
 - deploy

before_script:
 - docker info

build-nginx:
    stage: build
    except:
        refs:
            - master
    script:
     - docker build -t nginx-stretch $CI_PROJECT_DIR/nginx-stretch
     - docker tag nginx-stretch udienz/nginx:stretch

openmerge:
    image: udienz/gitlab-merge-resource
    before_script: []
    stage: deploy
    except:
        refs:
            - master
    script:
        - HOST=${CI_PROJECT_URL} CI_PROJECT_ID=${CI_PROJECT_ID} CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME} GITLAB_USER_ID=${GITLAB_USER_ID} PRIVATE_TOKEN=${PRIVATE_TOKEN} $CI_PROJECT_DIR/utils/merge.sh
    when: on_success

